// AUTO-GENERATED BY bun run ingest:assets. DO NOT EDIT DIRECTLY.

export type SpriteKey = 
  | 'hero_walk'
  | 'hero_slash'
  | 'hero_roll'
  | 'slime_meadow'
  | 'slime_spore'
  | 'boss_fungor'
  | 'npc_grandma'
  | 'npc_barnaby'
  | 'prop_pot'
  | 'prop_chest';

export type SoundKey = 
  | 'slash'
  | 'hit'
  | 'hurt'
  | 'coin'
  | 'pickup'
  | 'pot_lift'
  | 'pot_shatter'
  | 'chest_open'
  | 'victory_fanfare'
  | 'roll_dust'
  | 'boss_stomp';

export const REGISTERED_SPRITES: SpriteKey[] = [
  'hero_walk',
  'hero_slash',
  'hero_roll',
  'slime_meadow',
  'slime_spore',
  'boss_fungor',
  'npc_grandma',
  'npc_barnaby',
  'prop_pot',
  'prop_chest'
];

export const REGISTERED_AUDIO: SoundKey[] = [
  'slash',
  'hit',
  'hurt',
  'coin',
  'pickup',
  'pot_lift',
  'pot_shatter',
  'chest_open',
  'victory_fanfare',
  'roll_dust',
  'boss_stomp'
];
