import fs from 'fs';
import path from 'path';

/**
 * External Asset Ingestion & Typings Code-Gen Tool
 * Scans assets/raw/ for sprites and audio, generates TypeScript definitions,
 * and maintains asset manifests.
 */

const RAW_DIR = path.resolve(import.meta.dir, '../assets/raw');
const SPRITES_DIR = path.join(RAW_DIR, 'sprites');
const AUDIO_DIR = path.join(RAW_DIR, 'audio');
const OUTPUT_TYPES = path.resolve(import.meta.dir, '../shared/src/assetKeys.ts');

export function runAssetIngestion(): { sprites: string[]; audio: string[]; generatedFile: string } {
  // Ensure directories exist
  if (!fs.existsSync(SPRITES_DIR)) fs.mkdirSync(SPRITES_DIR, { recursive: true });
  if (!fs.existsSync(AUDIO_DIR)) fs.mkdirSync(AUDIO_DIR, { recursive: true });

  // Read raw files
  const spriteFiles = fs.readdirSync(SPRITES_DIR)
    .filter(f => f.endsWith('.png') || f.endsWith('.aseprite'))
    .map(f => path.parse(f).name);

  const audioFiles = fs.readdirSync(AUDIO_DIR)
    .filter(f => f.endsWith('.wav') || f.endsWith('.mp3') || f.endsWith('.ogg'))
    .map(f => path.parse(f).name);

  // Add default core engine keys so types are never empty
  const defaultSprites = [
    'hero_walk', 'hero_slash', 'hero_roll',
    'slime_meadow', 'slime_spore', 'boss_fungor',
    'npc_grandma', 'npc_barnaby', 'prop_pot', 'prop_chest'
  ];

  const defaultAudio = [
    'slash', 'hit', 'hurt', 'coin', 'pickup',
    'pot_lift', 'pot_shatter', 'chest_open',
    'victory_fanfare', 'roll_dust', 'boss_stomp'
  ];

  const allSprites = Array.from(new Set([...defaultSprites, ...spriteFiles]));
  const allAudio = Array.from(new Set([...defaultAudio, ...audioFiles]));

  // Generate TypeScript definitions
  const code = `// AUTO-GENERATED BY bun run ingest:assets. DO NOT EDIT DIRECTLY.

export type SpriteKey = 
${allSprites.map(s => `  | '${s}'`).join('\n')};

export type SoundKey = 
${allAudio.map(a => `  | '${a}'`).join('\n')};

export const REGISTERED_SPRITES: SpriteKey[] = [
${allSprites.map(s => `  '${s}'`).join(',\n')}
];

export const REGISTERED_AUDIO: SoundKey[] = [
${allAudio.map(a => `  '${a}'`).join(',\n')}
];
`;

  fs.writeFileSync(OUTPUT_TYPES, code, 'utf-8');

  return {
    sprites: allSprites,
    audio: allAudio,
    generatedFile: OUTPUT_TYPES
  };
}

if (import.meta.main) {
  console.log('🎨 Running BitQuest External Asset Ingestion & Typings Generator...');
  const res = runAssetIngestion();
  console.log(`- Registered Sprites: ${res.sprites.length} keys`);
  console.log(`- Registered Audio: ${res.audio.length} keys`);
  console.log(`- Type Definitions Generated: ${res.generatedFile}`);
  console.log('✨ Strongly-typed asset keys successfully synchronized!');
}
